### ISSUE TITLE
Improved documentation

### ISSUE THREAD

**Issue by omnidan** [omnidan/redux-undo#88]
- [x] set up gitbook (#89)
- [x] set up [redux-undo.js.org](https://redux-undo.js.org) 
- [x] FAQ page (e.g. debouncing: #70, syncing histories: #85)
- [ ] examples
- [x] describe what redux-undo does with the initialHistory (also see #43) 
- [x] guide to switch from 0.x to 1.0-beta (#73)

**Comment by nmay231** [comment]
I believe the heart of these issues has been fulfilled, though we _could_ do with more simple doc examples.

Adding [that task](https://github.com/omnidan/redux-undo/projects/1#card-30976066) to the Documentation project and closing.
